# This workflow will build a package using Gradle and then publish it to GitHub packages when a release is created
# For more information see: https://github.com/actions/setup-java/blob/main/docs/advanced-usage.md#Publishing-using-gradle

name: Gradle Package

on: push

jobs:
  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 8
      uses: actions/setup-java@v2
      with:
        java-version: '8' # LTS
        distribution: 'adopt'
        server-id: github # Value of the distributionManagement/repository/id field of the pom.xml
        persist-credentials: false

    - name: Build with Gradle
      run: gradlew build # No decomp/dev workspace setup needed.
      
    - name: Upload Release Build Artifact
      uses: actions/upload-artifact@v2
      with:
        name: Windows Gradlew Build
        path: |
          build/libs/
