name: Gradle Build
on: push

jobs:
  build:
    runs-on: ${{ matrix.os }}

    strategy:
        matrix:
            os: [windows-latest, macOS-latest, ubuntu-latest]

    # Skip job if a commit message contains "[skip build]"
    if: "!contains(github.event.head_commit.message, '[skip build]')"

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 8
      uses: actions/setup-java@v2
      with:
        java-version: '8' # LTS
        distribution: 'adopt'
        server-id: github

    - name: Restore Submodules
      run: git submodule update --init --recursive

    - name: Build with Gradle
      run:   |
          if [ "$RUNNER_OS" == "Linux" ] || [ "$RUNNER_OS" == "macOS" ]; then
              chmod +x ./sources/1.8/gradlew
              ./sources/1.8/gradlew build
          elif [ "$RUNNER_OS" == "Windows" ]; then
              ./sources/1.8/gradlew.bat build
          fi
      shell: bash
    - name: Upload Release Build Artifact
      uses: actions/upload-artifact@v2
      with:
        name: Artifacts
        path: |
          ./sources/1.8/build/libs/
