name: Gradle Build
on: push

jobs:
  build:
    runs-on: ubuntu-latest

    # Skip job if a commit message contains "[skip build]"
    if: "!contains(github.event.head_commit.message, '[skip build]')"

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 8
      uses: actions/setup-java@v2
      with:
        java-version: '8' # LTS
        distribution: 'adopt'

    - name: Restore Git submodules
      run: git submodule update --init --recursive

    - name: Build with Gradle
      run: ./gradlew build
      
    - name: Upload build artifact
      uses: actions/upload-artifact@v2
      with:
        name: Artifacts
        path: |
          build/libs/
